# Site settings
title: Casa Veggie
email: rosinanabazas@gmail.com
description: "Blog de recetas Vegetarianas"
baseurl: "/casa-veggie"
url: "https://rosinanabazas.github.io/casa-veggie/"
# url: "http://localhost:4000/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
